Adding support to filter columns for the Pod Metrics script
pixie-io/grafana-plugin pull request #45
Opened 2022-06-07 22:08 UTC by kpattaswamy

Added a drop down select option for a user to choose what columns to filter in the Pods-Metrics table. Did this by adding support to dynamically replace part of the px script dealing with displaying all columns with only columns chosen by user. 

Signed-off-by: Kartik Pattaswamy <kpattaswamy@pixielabs.ai>

2022-06-07 22:37 UTC, nserrino commented on src/column_filtering.tsx
> +
we should put these pod column options as a property of the JSON for each script. that way, we don't hard code a particular script into the UI - it's all configurable via JSON

2022-06-07 23:02 UTC, kpattaswamy commented on src/column_filtering.tsx
> +
Ok I'll add them as a property of JSON for the script

2022-06-08 17:44 UTC, TarasPriadka requested changes
A few stylistic and structural comments

2022-06-09 23:17 UTC, aimichelle commented on src/pxl_scripts.tsx
> +  columnOptions: scriptObject.columnNames,
For the `columnNames` field in the json files, it seems redundant to specify the `value` since arrays are inherently ordered anyway. 

I think restructuring the JSON file to just be:
` "columnNames": ["timestamp", "remote_addr", ...]`

Then here, we convert it to the values/label obj:
`columnOptions: scriptObject.columnNames.map((name, index) => { 'label': name, 'value': index  })`

2022-06-09 23:17 UTC, aimichelle commented on src/column_filtering.tsx
> +  const beforeDisplayCol = script.slice(0, script.indexOf('[['));
My worry here is if there's a script that uses `[[` and `]]` multiple times, and not just in the final output. For example, if you take a look at the `px/cluster` script's `conn_stats_by_service` function.

Luckily these scripts are written by ourselves, so we can make sure that doesn't happen. But we may to be a bit more robust and search for the last indexOf `[[` and `]]`. You can use `lastIndexOf` for this.

2022-06-10 20:39 UTC, NickLanam reviewed
Largely LGTM, just a couple of questions (see below)

2022-06-10 20:39 UTC, NickLanam commented on tsconfig.json
> +    "lib": ["es2021", "dom"],
I'm surprised nothing was breaking yet without these, interesting. What finally started creating errors that made you need to put this in?

2022-06-10 20:39 UTC, NickLanam commented on src/query_editor.tsx
> +          {query.isTabular === true ? (
Since the other path is just an empty fragment, you can even just do `query.isTabular && (...)` and not have a ternary at all. React renders nothing at all if it's told to render a literal `false`, so `a && b` resolves to either rendering nothing or rendering `b`.

2022-06-10 20:39 UTC, NickLanam commented on src/column_filtering.tsx
> +  const beforeDisplayCol = script.slice(0, script.indexOf('[['));
I'm in agreement that scanning for this substring seems uncomfortably fragile. Template variables like you're already doing in `datasource.tsx` (or some other format that is definitely not valid PxL) are a more robust choice here since you're controlling the preset scripts in this same repository. `px/cluster`, as mentioned, has at least three `[[something]]`s in it, how do you know for sure which one should be used?

2022-06-10 20:39 UTC, TarasPriadka requested changes
Looks good overall. Had some small nits

2022-06-10 20:39 UTC, TarasPriadka commented on src/column_filtering.tsx
> +  const beforeDisplayCol = script.slice(0, script.lastIndexOf('[['));
Maybe we can introduce some sort of macro which users can use to specify the column names? We can find that macro then and process it in a predictable way.
Ex. 
```
...
COLUMNS{all} // or COLUMNS{'pod', 'namespace', 'latency', ...}
...
```
Then later find this macro in code, process the columns that users want to display, and replace this macro with `df.display` in `query.pxlScript` before sending the code query.

2022-06-10 20:39 UTC, TarasPriadka commented on src/column_filtering.tsx
> +      filteredColumnScript += formatColumnName(chosenOptions[i].label);
You already have a method which does this.

```suggestion
    //Dynamically builds the script by concatenating each option that was chosen
    filteredColumnScript = getAllColumnScript(chosenOptions);
```

2022-06-10 20:39 UTC, TarasPriadka commented on src/column_filtering.tsx
> +}
Can join an array of values, and also should probably name this something general like `getScriptFromColumns`:

```suggestion
function getScriptFromColumns(columnNames: Array<{ label: string; value: number }>): string {
    return [
        '[[', 
        ...columnNames.map(colName=>`'${colName.label}'`),
        ']]'
    ].join()
}
```
This basically constructs your string where the mid part just formats `colNames` the way you want.

2022-06-10 20:39 UTC, TarasPriadka commented on src/datasource.ts
> +      query.pxlScript = query.pxlScript.replaceAll(replace[0], replace[1]);
For readability, can do something like 
```suggestion
    for (const [changeFrom, changeTo] of timeVars) {
        query.pxlScript = query.pxlScript.replaceAll(replaceFrom, replaceTo);
    }
```

2022-06-10 20:39 UTC, TarasPriadka commented on src/pxl_scripts.tsx
> +  columnNames: string[];
Since these may be not present in some scripts, you can make these fields optional.
```suggestion
  isTabular?: boolean;
  columnNames?: string[];
```

2022-06-10 20:39 UTC, TarasPriadka commented on src/pxl_scripts.tsx
> +  columnOptions: (scriptObject.columnNames || []).map((name, index) => ({ label: name, value: index })),
These are already a part of `scriptObject`, so you don't need to add these as fields. Also `SelectableValue` doesn't have these fields, so its better to avoid adding them directly to the object.

2022-06-10 20:39 UTC, TarasPriadka commented on src/query_editor.tsx
> +      const script = option.value;
```suggestion
      const script:Script = option.value;
```

2022-06-10 20:39 UTC, TarasPriadka commented on src/query_editor.tsx
> +              onChange={this.filterColumns.bind(this)}
In React you want to call functions which get called on change or on click as `on[name of action which is happening]`. So in this case you could call this method `onFilterSelect`.

2022-06-10 20:41 UTC, TarasPriadka commented on tsconfig.json
> +    "lib": ["es2021", "dom"],
The `String.replaceAll(...)` wasn't present for the older version of es.

2022-06-10 20:45 UTC, TarasPriadka commented on src/column_filtering.tsx
> +  const beforeDisplayCol = script.slice(0, script.indexOf('[['));
We could try creating some macro which is easy to find without collisions with user code. https://github.com/pixie-io/grafana-plugin/pull/45#discussion_r894856363

2022-06-13 23:33 UTC, aimichelle commented on src/datasource.ts
> +    let timeVars = [
Javascript has variables can be defined as `let` or `const`. 
`let` is usually used when you know the variable is going to be reassigned:
```
let a = 1; 
a = 2;
```
However, `const` should be used when you essentially have a constant. 
```
const a = 1;
a = 2; // You shouldn't do this!
```

In the case of `timeVars`, this can be a const. And `columnVars` below as well.
You can actually pull them out of this function and move them to the top of the file (defined on the same level as functions). In general, we like to pull out constants to the top so that they're easy to find and change if needbe.

2022-06-13 23:33 UTC, aimichelle commented on src/datasource.ts
> +    //Replace Grafana's time global variables from the script with Pixie's time macros
Nit: We like to make sure theres a space after the `//` in our comments. So this should be: `// Replace Grafana's...`
 
This is usually enforced by a linter, so let me look into why that's not set up yet so that it's easier to keep in mind for your next PRs.

2022-06-13 23:33 UTC, aimichelle commented on src/types.ts
> +  columnOptions: Array<{ label: string; value: number }>;
This is a good suggestion.

2022-06-14 00:49 UTC, aimichelle approved these changes

2022-06-14 21:50 UTC, NickLanam approved these changes

2022-06-14 21:51 UTC, aimichelle approved these changes

2022-06-14 22:04 UTC, merged