Adding Feature to Groupby
pixie-io/grafana-plugin pull request #56
Opened 2022-06-28 18:26 UTC by kpattaswamy

This feature allows a user to select certain columns in a table to groupby as well as present an option to choose whether or not to aggregate by certain columns/function pairs as well. A user does not have to select an aggregate pair to perform groupby.

<img width="1896" alt="initial-view" src="https://user-images.githubusercontent.com/62078498/176255532-f06fdffd-28fc-4fec-952e-0f44082c5918.png">
<img width="1901" alt="groupby-selected" src="https://user-images.githubusercontent.com/62078498/176255594-9eeae79a-7db1-4782-8288-62d5a3f10c33.png">
<img width="1903" alt="aggregate-selected" src="https://user-images.githubusercontent.com/62078498/176255616-f74a4c30-bf18-4e88-965c-e5892b7ac7d5.png">

2022-06-28 18:54 UTC, philkuz reviewed
Mainly style nits from me. I think you'll want a review from another project member for more typescript specific things as well.

2022-06-28 18:54 UTC, philkuz commented on src/groupby.tsx
> +  return script;
We like writing code w/ the following pattern
Basically remove indentation, invert if statement, and return early to simplify the logic.

```suggestion
  if (chosenOptions.length == 0) {
    return script;
  }
  let columns: string = chosenOptions
    .map((columnName: { label: string; value: number }) => `'${columnName.label}'`)
    .join();
  script = `df = df.groupby([` + columns + `])`;
  let aggScript = '.agg()\npx.display(df)';

  // Update aggScript if the user chose any aggregate options
  if (chosenAggPairs.length > 0) {
    let aggPairs: string = chosenAggPairs
      .map(
        (aggPair: { aggColumn: string; aggFunction: string }) =>
          `${aggPair.aggColumn}_${aggPair.aggFunction}=('${aggPair.aggColumn}',px.${aggPair.aggFunction})`
      )
      .join();
    aggScript = '.agg(' + aggPairs + ')\npx.display(df)';
  }
  return script + aggScript;
```

2022-06-28 18:54 UTC, philkuz commented on src/groupby.tsx
> +  }
similar to above, don't use else statement just do the return after the if statement.

2022-06-28 18:54 UTC, philkuz commented on src/groupby.tsx
> +    }
rewrite all of these to do an early return if statement instead of the Keep everything indented form. That's more our style.

2022-06-28 18:54 UTC, philkuz commented on src/groupby.tsx
> +  }
function on line 43 is actually a good example of what  I mean

2022-06-28 23:07 UTC, NickLanam requested changes
Generally good; just a handful of minor code smells and a visual tweak.

2022-06-28 23:07 UTC, NickLanam commented on src/groupby.tsx
> +export function getAggValues(name: string): { label: string; value: number } | undefined {
Nit: we usually use `null` rather than `undefined` for return values. Either of them works for what you're doing here; it's just a convention thing.

Also, the empty string is falsey, so you can do `return name ? { label: name, value: 0 } : null`

2022-06-28 23:07 UTC, NickLanam commented on src/groupby.tsx
> +            <HorizontalGroup key={index}>
We could benefit from some visual padding between items that aren't part of the same control.

2022-06-28 23:07 UTC, NickLanam commented on src/query_editor.tsx
> +          {query.queryMeta?.isGroupBy ? (
When the false case is an empty fragment (happens elsewhere in this file too), you can do `{condition && (<SomeStuff />)}` instead of a ternary. React knows not to render anything for `false` and `null`.

2022-06-30 20:03 UTC, NickLanam approved these changes
Looks great now!

2022-06-30 22:07 UTC, aimichelle approved these changes

2022-06-30 22:07 UTC, merged